[package]
name = "uecho"
version = "0.1.0"
authors = ["The uecho-rs Authors <skonno@cybergarage.org>"]
edition = "2021"

[dependencies]
log = "0.4"
chrono = "0.4"
hex = "0.4"
pnet = "0.28.0"
strum = "0.21"
strum_macros = "0.21"
once_cell = "1.14.0"
socket2 = "0.4.5"
nix = "0.25.0" 

[[bin]]
name = "uechosearch"
path = "bin/uechosearch.rs"
