[package]
name = "echonet"
version = "1.2.7"
authors = ["The uecho-rs Authors <skonno@cybergarage.org>"]
edition = "2021"
readme = "README.md"
homepage = "http://www.cybergarage.org/"
repository = "https://github.com/cybergarage/uecho-rs"
license = "Apache-2.0"
# license-file = "LICENSE"
description = "ECHONET Lite framework for Rust"
categories = ["network-programming"]
keywords = ["echonet", "echonet-lite"]

[features]
default = ["std"]
std = ["unix", "dep:uuid"]
no_std = []
unix = ["dep:pnet", "dep:ipnetwork", "dep:nix", "dep:net2"]
esp = []

[dependencies]
log = {version = "0.4", default-features = false}
hex = "0.4"
strum = "0.25"
strum_macros = "0.25"
once_cell = "1.14.0"
chrono = "0.4"
pnet = { version = "0.28.0", optional = true }
ipnetwork = { version = "0.16.0", optional = true }
nix = { version = "0.25.0", optional = true }
net2 = { version = "0.2", optional = true }
uuid = { version = "1.4.1", features = ["v4"], optional = true }

[target.'cfg(esp)'.dependencies]
esp-idf-sys = { version = "0.31.11", features = ["binstart"] }

[dev-dependencies]
signal-hook = "0.3.14"

[[example]]
name = "uechosearch"
path = "examples/uechosearch/uechosearch.rs"

[[example]]
name = "uechopost"
path = "examples/uechopost/uechopost.rs"

[[example]]
name = "uechobench"
path = "examples/uechobench/uechobench.rs"

[[example]]
name = "monolight"
path = "examples/monolight/monolight.rs"
