[package]
name = "echonet"
version = "1.2.7"
authors = ["The uecho-rs Authors <skonno@cybergarage.org>"]
edition = "2021"
readme = "README.md"
homepage = "http://www.cybergarage.org/"
repository = "https://github.com/cybergarage/uecho-rs"
license = "Apache-2.0"
# license-file = "LICENSE"
description = "ECHONET Lite framework for Rust"
categories = ["network-programming"]
keywords = ["echonet", "echonet-lite"]

[features]
default = ["std"]
std = ["unix"]
no_std = []
unix = []
esp = []

[dependencies]
log = "0.4"
hex = "0.4"
strum = "0.21"
strum_macros = "0.21"
once_cell = "1.14.0"
nix = "0.25.0" 
net2 = "0.2"
chrono = "0.4"

[target.'cfg(unix)'.dependencies]
pnet = "0.28.0"

[target.'cfg(esp)'.dependencies]
esp-idf-sys = { version = "0.31.11", features = ["binstart"] }

[dev-dependencies]
signal-hook = "0.3.14"

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[[example]]
name = "uechosearch"
path = "examples/uechosearch/uechosearch.rs"

[[example]]
name = "uechopost"
path = "examples/uechopost/uechopost.rs"

[[example]]
name = "uechobench"
path = "examples/uechobench/uechobench.rs"

[[example]]
name = "monolight"
path = "examples/monolight/monolight.rs"
