[package]
name = "uecho"
version = "0.1.0"
authors = ["The uecho-rs Authors <skonno@cybergarage.org>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
hex = "0.4"
pnet = "0.28.0"
net2 = "0.2"
strum = "0.21"
strum_macros = "0.21"
